import { FamilyMember, Prescription, HealthRecord, User } from '../types';

export const INITIAL_USER: User = {
  id: 'usr-sarah-101',
  name: 'Sarah Jenkins, MPH',
  email: 'sarah.jenkins@dawaaiirx.care',
  role: 'primary_user',
  phone: '+1 (555) 438-9210',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
  createdAt: '2026-01-15T09:00:00Z',
  token: 'mock-jwt-header.eyJzdWIiOiJ1c3Itc2FyYWgtMTAxIiwibmFtZSI6IlNhcmFoIEplbmtpbnMiLCJyb2xlIjoicHJpbWFyeV91c2VyIiwiaWF0IjoxNzg3MDI2NDAwLCJleHAiOjE3ODcwODQwMDB9.signature-valid',
};

export const DEMO_FAMILY_USERS: User[] = [
  INITIAL_USER,
  {
    id: 'usr-ethan-102',
    name: 'Ethan Jenkins (Spouse)',
    email: 'ethan.jenkins@dawaaiirx.care',
    role: 'family_member',
    phone: '+1 (555) 438-9211',
    memberId: 'mem-ethan-01',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    createdAt: '2026-02-01T10:00:00Z',
    token: 'mock-jwt-header.eyJzdWIiOiJ1c3ItZXRoYW4tMTAyIiwibmFtZSI6IkV0aGFuIEplbmtpbnMiLCJyb2xlIjoiZmFtaWx5X21lbWJlciIsImlhdCI6MTc4NzAyNjQwMCwiZXhwIjoxNzg3MDg0MDAwfQ.signature-valid',
  },
];

export const INITIAL_MEMBERS: FamilyMember[] = [
  {
    id: 'primary',
    name: 'Sarah Jenkins (Me)',
    relation: 'Self (Supervisor)',
    age: 38,
    gender: 'Female',
    bloodGroup: 'O+',
    allergies: ['Penicillin', 'Sulfa Drugs'],
    emergencyContact: 'Ethan (Spouse): +1 (555) 438-9211',
    avatarColor: 'bg-emerald-600 text-white',
    isPrimary: true,
    notes: 'Primary health supervisor for Jenkins household. Manages pediatric and geriatric care schedules.',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'mem-ethan-01',
    name: 'Ethan Jenkins',
    relation: 'Spouse',
    age: 40,
    gender: 'Male',
    bloodGroup: 'A+',
    allergies: ['Shellfish'],
    emergencyContact: 'Sarah: +1 (555) 438-9210',
    avatarColor: 'bg-teal-600 text-white',
    isPrimary: false,
    notes: 'Hypertension maintenance protocol and routine lipid management.',
    createdAt: '2026-01-16T10:30:00Z',
  },
  {
    id: 'mem-maya-02',
    name: 'Maya Jenkins',
    relation: 'Daughter',
    age: 10,
    gender: 'Female',
    bloodGroup: 'O+',
    allergies: ['Peanuts (Severe - EpiPen Carrier)', 'Tree Pollen'],
    emergencyContact: 'Mom: +1 (555) 438-9210',
    avatarColor: 'bg-rose-500 text-white',
    isPrimary: false,
    notes: 'Mild persistent pediatric asthma. School nurse has backup inhaler.',
    createdAt: '2026-01-18T14:15:00Z',
  },
  {
    id: 'mem-leo-03',
    name: 'Leo Jenkins',
    relation: 'Son',
    age: 7,
    gender: 'Male',
    bloodGroup: 'A+',
    allergies: ['Amoxicillin (Skin Rash)'],
    emergencyContact: 'Dad: +1 (555) 438-9211',
    avatarColor: 'bg-amber-500 text-white',
    isPrimary: false,
    notes: 'Seasonal eczema and general pediatric wellness vitamins.',
    createdAt: '2026-01-20T11:45:00Z',
  },
  {
    id: 'mem-martha-04',
    name: 'Martha Jenkins',
    relation: 'Mother',
    age: 68,
    gender: 'Female',
    bloodGroup: 'B+',
    allergies: ['Codeine', 'NSAIDs (Stomach upset)'],
    emergencyContact: 'Sarah: +1 (555) 438-9210',
    avatarColor: 'bg-indigo-600 text-white',
    isPrimary: false,
    notes: 'Type 2 diabetes & Osteoarthritis management. Requires weekly pillbox monitoring.',
    createdAt: '2026-02-05T16:20:00Z',
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-01',
    memberId: 'mem-martha-04',
    memberName: 'Martha Jenkins',
    memberRelation: 'Mother',
    medicineName: 'Metformin HCl 500mg ER',
    genericName: 'Metformin Extended Release',
    dosage: '500 mg (1 tablet)',
    form: 'Tablet',
    frequency: 'Twice daily',
    scheduleTimes: ['Morning', 'Evening'],
    instructions: 'Take immediately after morning breakfast and dinner with a full glass of water.',
    prescribedBy: 'Dr. Raymond Holt, MD (Endocrinology)',
    prescribedDate: '2026-07-20',
    startDate: '2026-07-21',
    endDate: '2026-10-21',
    enableRefillReminder: true,
    refillReminderDate: '2026-08-22', // Refill due soon (within 3 days of local date)
    totalQuantity: 60,
    remainingQuantity: 6, // Low supply
    lowStockThreshold: 10,
    refillRxNumber: 'RX-992841-B',
    pharmacyName: 'Walgreens Pharmacy #4412',
    pharmacyPhone: '+1 (555) 892-3000',
    status: 'Refill Due',
    takenHistory: [
      { date: '2026-08-19', timeSlot: 'Morning', loggedAt: '2026-08-19T08:15:00Z' },
    ],
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-08-19T08:15:00Z',
  },
  {
    id: 'rx-02',
    memberId: 'mem-ethan-01',
    memberName: 'Ethan Jenkins',
    memberRelation: 'Spouse',
    medicineName: 'Lisinopril 20mg',
    genericName: 'Lisinopril',
    dosage: '20 mg (1 tablet)',
    form: 'Tablet',
    frequency: 'Once daily',
    scheduleTimes: ['Morning'],
    instructions: 'Take every morning around 8:00 AM. Monitor blood pressure weekly.',
    prescribedBy: 'Dr. Evelyn Martinez, MD (Cardiology)',
    prescribedDate: '2026-06-10',
    startDate: '2026-06-11',
    endDate: '2026-12-11',
    enableRefillReminder: true,
    refillReminderDate: '2026-08-20', // Refill tomorrow!
    totalQuantity: 90,
    remainingQuantity: 3, // Urgent refill
    lowStockThreshold: 7,
    refillRxNumber: 'RX-884129-C',
    pharmacyName: 'CVS Caremark Central #108',
    pharmacyPhone: '+1 (555) 743-1990',
    status: 'Urgent Refill',
    takenHistory: [
      { date: '2026-08-19', timeSlot: 'Morning', loggedAt: '2026-08-19T07:45:00Z' },
    ],
    createdAt: '2026-06-10T11:00:00Z',
    updatedAt: '2026-08-19T07:45:00Z',
  },
  {
    id: 'rx-03',
    memberId: 'mem-maya-02',
    memberName: 'Maya Jenkins',
    memberRelation: 'Daughter',
    medicineName: 'Albuterol Sulfate HFA Inhaler',
    genericName: 'Albuterol Inhalation Aerosol',
    dosage: '90 mcg/actuation (2 puffs)',
    form: 'Inhaler',
    frequency: 'As needed (PRN)',
    scheduleTimes: ['Morning', 'Afternoon'],
    instructions: 'Inhale 2 puffs every 4-6 hours as needed for shortness of breath or before PE class.',
    prescribedBy: 'Dr. Keith Vance, MD (Pediatrics)',
    prescribedDate: '2026-05-15',
    startDate: '2026-05-15',
    endDate: '2027-05-15',
    enableRefillReminder: true,
    refillReminderDate: '2026-09-10',
    totalQuantity: 200,
    remainingQuantity: 142,
    lowStockThreshold: 30,
    refillRxNumber: 'RX-441029-A',
    pharmacyName: 'Walgreens Pharmacy #4412',
    pharmacyPhone: '+1 (555) 892-3000',
    status: 'Active',
    takenHistory: [],
    createdAt: '2026-05-15T09:30:00Z',
    updatedAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'rx-04',
    memberId: 'primary',
    memberName: 'Sarah Jenkins (Me)',
    memberRelation: 'Self (Supervisor)',
    medicineName: 'Levothyroxine Sodium 75mcg',
    genericName: 'Levothyroxine',
    dosage: '75 mcg (1 tablet)',
    form: 'Tablet',
    frequency: 'Once daily',
    scheduleTimes: ['Morning'],
    instructions: 'Take 30-60 minutes before breakfast with plain water on an empty stomach.',
    prescribedBy: 'Dr. Raymond Holt, MD',
    prescribedDate: '2026-04-02',
    startDate: '2026-04-03',
    endDate: '2027-04-03',
    enableRefillReminder: true,
    refillReminderDate: '2026-08-30',
    totalQuantity: 90,
    remainingQuantity: 22,
    lowStockThreshold: 10,
    refillRxNumber: 'RX-102948-Z',
    pharmacyName: 'CVS Caremark Central #108',
    pharmacyPhone: '+1 (555) 743-1990',
    status: 'Active',
    takenHistory: [
      { date: '2026-08-19', timeSlot: 'Morning', loggedAt: '2026-08-19T06:30:00Z' },
    ],
    createdAt: '2026-04-02T08:00:00Z',
    updatedAt: '2026-08-19T06:30:00Z',
  },
  {
    id: 'rx-05',
    memberId: 'mem-leo-03',
    memberName: 'Leo Jenkins',
    memberRelation: 'Son',
    medicineName: 'Pediatric Daily Multivitamin + Zinc',
    genericName: 'Children Multivitamin Gummies',
    dosage: '1 gummy chewable',
    form: 'Tablet',
    frequency: 'Once daily',
    scheduleTimes: ['Morning'],
    instructions: 'Chew thoroughly after breakfast.',
    prescribedBy: 'Dr. Keith Vance, MD (Pediatrics)',
    prescribedDate: '2026-08-01',
    startDate: '2026-08-01',
    endDate: '2026-11-01',
    enableRefillReminder: false,
    totalQuantity: 60,
    remainingQuantity: 42,
    lowStockThreshold: 10,
    status: 'Active',
    takenHistory: [],
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-15T09:00:00Z',
  }
];

export const INITIAL_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: 'rec-01',
    memberId: 'primary',
    memberName: 'Sarah Jenkins (Me)',
    memberRelation: 'Self (Supervisor)',
    title: 'Severe Penicillin Allergy Documentation',
    category: 'Allergy & Adverse Reaction',
    dateRecorded: '2026-03-12',
    doctorOrClinic: 'Mercy Medical Center Allergy & Immunology',
    details: 'Patient developed diffuse urticaria, facial angioedema, and wheezing within 30 minutes of oral Amoxicillin administration during dental procedure in 2021. Avoid all beta-lactam antibiotics.',
    severity: 'Critical',
    tags: ['Penicillin', 'Anaphylactoid', 'High Alert'],
    attachments: [
      { name: 'Allergy_SkinPrick_Report.pdf', size: '1.2 MB', type: 'application/pdf' },
    ],
    createdAt: '2026-03-12T14:30:00Z',
  },
  {
    id: 'rec-02',
    memberId: 'mem-ethan-01',
    memberName: 'Ethan Jenkins',
    memberRelation: 'Spouse',
    title: 'Annual Cardiovascular Checkup & Lipid Panel',
    category: 'Doctor Visit & Consultation',
    dateRecorded: '2026-07-15',
    doctorOrClinic: 'Dr. Evelyn Martinez, MD - St. Luke Cardiology Group',
    details: 'Routine follow-up for Stage 1 Hypertension. Patient reporting excellent adherence to Lisinopril 20mg. Blood pressure well controlled at 122/78 mmHg. Resting ECG shows normal sinus rhythm.',
    severity: 'Mild',
    vitals: {
      bloodPressure: '122/78 mmHg',
      heartRate: '68 bpm',
      bloodGlucose: '94 mg/dL',
      weight: '82.5 kg',
      spO2: '99%',
    },
    tags: ['Cardiology', 'Hypertension', 'Normal ECG'],
    attachments: [
      { name: 'Lipid_Panel_Results_July2026.pdf', size: '840 KB', type: 'application/pdf' },
      { name: 'ECG_Tracing_Record.pdf', size: '2.4 MB', type: 'application/pdf' }
    ],
    createdAt: '2026-07-15T11:00:00Z',
  },
  {
    id: 'rec-03',
    memberId: 'mem-maya-02',
    memberName: 'Maya Jenkins',
    memberRelation: 'Daughter',
    title: 'Pediatric Asthma Management Plan 2026-2027',
    category: 'Chronic Condition Management',
    dateRecorded: '2026-08-05',
    doctorOrClinic: 'Dr. Keith Vance, MD - Valley Children Health',
    details: 'Asthma action plan updated for upcoming school year. Peak flow baseline is 280 L/min. Green zone > 225 L/min. Prescribed Albuterol HFA for symptom relief and pre-exercise prophylaxis.',
    severity: 'Moderate',
    vitals: {
      heartRate: '84 bpm',
      temperature: '98.4 °F',
      spO2: '98%',
      weight: '32 kg',
    },
    tags: ['Pediatric Asthma', 'Peak Flow', 'School Action Plan'],
    attachments: [
      { name: 'School_Asthma_Form_Signed.pdf', size: '1.8 MB', type: 'application/pdf' }
    ],
    createdAt: '2026-08-05T15:20:00Z',
  },
  {
    id: 'rec-04',
    memberId: 'mem-martha-04',
    memberName: 'Martha Jenkins',
    memberRelation: 'Mother',
    title: 'Quarterly HbA1c & Comprehensive Metabolic Panel',
    category: 'Lab & Diagnostic Report',
    dateRecorded: '2026-08-10',
    doctorOrClinic: 'Quest Diagnostics Regional Lab',
    details: 'HbA1c measured at 6.8% (Target < 7.0% for geriatric diabetic control). eGFR 74 mL/min/1.73m2 (stable renal function). Fasting glucose 118 mg/dL. Metformin dose appropriate.',
    severity: 'Moderate',
    vitals: {
      bloodPressure: '128/82 mmHg',
      bloodGlucose: '118 mg/dL',
      weight: '64 kg',
    },
    tags: ['Diabetes', 'HbA1c', 'Lab Results'],
    attachments: [
      { name: 'Quest_LabReport_Aug2026.pdf', size: '620 KB', type: 'application/pdf' }
    ],
    createdAt: '2026-08-10T16:00:00Z',
  },
  {
    id: 'rec-05',
    memberId: 'mem-leo-03',
    memberName: 'Leo Jenkins',
    memberRelation: 'Son',
    title: '7-Year Pediatric Well-Child Exam & DTaP Booster',
    category: 'Vaccination / Immunization',
    dateRecorded: '2026-06-22',
    doctorOrClinic: 'Dr. Keith Vance, MD - Valley Children Health',
    details: 'Normal growth percentiles (Height 65th, Weight 58th). Received annual influenza immunization and booster vaccines. Cleared for all youth soccer activities.',
    severity: 'Mild',
    vitals: {
      temperature: '98.6 °F',
      heartRate: '90 bpm',
      weight: '24 kg',
    },
    tags: ['Vaccination', 'Well-Child', 'Clearance'],
    attachments: [
      { name: 'Immunization_Record_Card.pdf', size: '450 KB', type: 'application/pdf' }
    ],
    createdAt: '2026-06-22T10:15:00Z',
  }
];
